name = "smail"
version = "1.0.0"

description = "Write HTML compliant email with peace of mind like Lustre 😌"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gungun974", repo = "smail" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
houdini = ">= 1.2.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
